export const FETCH_BOARDS = 'FETCH_BOARDS';
export const FETCH_PARTICULAR_BOARD = 'FETCH_PARTICULAR_BOARD';
export const FETCH_LISTS = 'FETCH_LISTS';
export const FETCH_CARDS = 'FETCH_CARDS';
export const FETCH_CHECKLISTS = 'FETCH_CHECKLISTS';
export const NEW_BOARDS = 'NEW_BOARD';
export const CREATE_CARD = 'CREATE_CARD';
